import org.mariadb.jdbc.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.mariadb.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author muraf
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form FormPemesanan
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelaminGrup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        mainContent = new javax.swing.JTabbedPane();
        jadwalTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        pemesananTab = new javax.swing.JPanel();
        mainClassTab = new javax.swing.JTabbedPane();
        ekonomiTab = new javax.swing.JPanel();
        gambarBusEkonomi = new javax.swing.JLabel();
        tanggalEkonomi = new javax.swing.JComboBox<>();
        waktuEkonomi = new javax.swing.JComboBox<>();
        jumlahDewasaEkonomi = new javax.swing.JSpinner();
        jumlahAnakEkonomi = new javax.swing.JSpinner();
        hargaKelasEkonomi = new javax.swing.JTextArea();
        hargaTotalEkonomi = new javax.swing.JTextField();
        syaratKetentuanEkonomi = new javax.swing.JCheckBox();
        labelTanggalEksekutif1 = new javax.swing.JLabel();
        labelWaktuEksekutif1 = new javax.swing.JLabel();
        labelDewasa1 = new javax.swing.JLabel();
        labelAnak1 = new javax.swing.JLabel();
        labelKelas1 = new javax.swing.JLabel();
        labelTotal1 = new javax.swing.JLabel();
        tombolPesanKelasEkonomi = new javax.swing.JButton();
        tombolCekHargaKelasEkonomi = new javax.swing.JButton();
        bisnisTab = new javax.swing.JPanel();
        gambarBusBisnis = new javax.swing.JLabel();
        tanggalBisnis = new javax.swing.JComboBox<>();
        waktuBisnis = new javax.swing.JComboBox<>();
        jumlahDewasaBisnis = new javax.swing.JSpinner();
        jumlahAnakBisnis = new javax.swing.JSpinner();
        hargaKelas2 = new javax.swing.JTextArea();
        hargaTotalBisnis = new javax.swing.JTextField();
        syaratKetentuanBisnis = new javax.swing.JCheckBox();
        labelTanggalEksekutif2 = new javax.swing.JLabel();
        labelWaktuEksekutif2 = new javax.swing.JLabel();
        labelDewasa2 = new javax.swing.JLabel();
        labelAnak2 = new javax.swing.JLabel();
        labelKelas2 = new javax.swing.JLabel();
        labelTotal2 = new javax.swing.JLabel();
        tombolPesanKelasBisnis = new javax.swing.JButton();
        tombolCekHargaKelasBisnis = new javax.swing.JButton();
        eksekutifTab = new javax.swing.JPanel();
        tanggalEksekutif = new javax.swing.JComboBox<>();
        waktuEksekutif = new javax.swing.JComboBox<>();
        jumlahDewasaEksekutif = new javax.swing.JSpinner();
        jumlahAnakEksekutif = new javax.swing.JSpinner();
        hargaKelas = new javax.swing.JTextArea();
        hargaTotalEksekutif = new javax.swing.JTextField();
        syaratKetentuanEksekutif = new javax.swing.JCheckBox();
        labelTanggalEksekutif = new javax.swing.JLabel();
        labelWaktuEksekutif = new javax.swing.JLabel();
        labelDewasa = new javax.swing.JLabel();
        labelAnak = new javax.swing.JLabel();
        labelKelas = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        tombolPesanKelasEksekutif = new javax.swing.JButton();
        gambar = new javax.swing.JLabel();
        tombolCekHargaKelasEksekutif = new javax.swing.JButton();
        riwayatTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_riwayat_pesanan = new javax.swing.JTable();
        btnLihatRiwayat = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bus ekonomi.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(142, 128, 106));

        mainContent.setBackground(new java.awt.Color(173, 139, 115));
        mainContent.setForeground(new java.awt.Color(255, 251, 233));
        mainContent.setToolTipText("");
        mainContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainContent.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N

        jadwalTab.setBackground(new java.awt.Color(255, 230, 188));
        jadwalTab.setForeground(new java.awt.Color(255, 255, 255));
        jadwalTab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jadwalTab.setFocusable(false);
        jadwalTab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jadwalTabFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("TANGGAL");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selasa, 11 Oktober 2022", "Rabu, 12 Oktober 2022", "Kamis, 13 Oktober 2022" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Pagi (08:00 WIB)\n- Kelas Ekonomi: Bus Renjana Asmara Eko.\n- Kelas Bisnis: Bus Bentala Nadir Bis.\n- Kelas Eksekutif: Bus Angga Buana Eks.\n\nSiang (12:30 WIB)\n- Kelas Ekonomi: -\n- Kelas Bisnis: Bus Semburat Lembayung Bis.\n- Kelas Eksekutif: Bus Dirgantara Eks.\n\nMalam (19:30)\n- Kelas Ekonomi: -\n- Kelas Bisnis: -\n- Kelas Eksekutif: Bus Purnama Suci Eks.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("JADWAL");

        javax.swing.GroupLayout jadwalTabLayout = new javax.swing.GroupLayout(jadwalTab);
        jadwalTab.setLayout(jadwalTabLayout);
        jadwalTabLayout.setHorizontalGroup(
            jadwalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadwalTabLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jadwalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jadwalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jadwalTabLayout.setVerticalGroup(
            jadwalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadwalTabLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jadwalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jadwalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        mainContent.addTab("JADWAL", jadwalTab);

        pemesananTab.setBackground(new java.awt.Color(255, 251, 233));

        mainClassTab.setBackground(new java.awt.Color(206, 171, 147));
        mainClassTab.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        mainClassTab.setForeground(new java.awt.Color(102, 90, 72));
        mainClassTab.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        ekonomiTab.setBackground(new java.awt.Color(255, 251, 233));

        gambarBusEkonomi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bus ekonomi.jpg"))); // NOI18N
        gambarBusEkonomi.setPreferredSize(new java.awt.Dimension(490, 290));

        tanggalEkonomi.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        tanggalEkonomi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selasa, 11 Oktober 2022", "Rabu, 12 Oktober 2022", "Kamis, 13 Oktober 2022" }));
        tanggalEkonomi.setToolTipText("");
        tanggalEkonomi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        waktuEkonomi.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        waktuEkonomi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagi (08:00 WIB)" }));
        waktuEkonomi.setToolTipText("");
        waktuEkonomi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        waktuEkonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktuEkonomiActionPerformed(evt);
            }
        });

        jumlahDewasaEkonomi.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jumlahAnakEkonomi.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        hargaKelasEkonomi.setEditable(false);
        hargaKelasEkonomi.setColumns(20);
        hargaKelasEkonomi.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        hargaKelasEkonomi.setRows(5);
        hargaKelasEkonomi.setText("Anak-Anak\t: Rp75.000,00/orang\nDewasa\t: Rp100.000,00/orang");

        hargaTotalEkonomi.setEditable(false);
        hargaTotalEkonomi.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        hargaTotalEkonomi.setText("Rp0");
        hargaTotalEkonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaTotalEkonomiActionPerformed(evt);
            }
        });

        syaratKetentuanEkonomi.setText("Saya menyetujui syarat dan ketentuan yang berlaku");
        syaratKetentuanEkonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syaratKetentuanEkonomiActionPerformed(evt);
            }
        });

        labelTanggalEksekutif1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTanggalEksekutif1.setText("Pilih Tanggal");

        labelWaktuEksekutif1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelWaktuEksekutif1.setLabelFor(waktuEksekutif);
        labelWaktuEksekutif1.setText("Pilih Waktu");

        labelDewasa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDewasa1.setText("Jumlah orang dewasa");

        labelAnak1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelAnak1.setText("Jumlah anak kecil (< 12)");

        labelKelas1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelKelas1.setText("Harga Kelas");

        labelTotal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTotal1.setText("Total Bayar");

        tombolPesanKelasEkonomi.setBackground(new java.awt.Color(102, 90, 72));
        tombolPesanKelasEkonomi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tombolPesanKelasEkonomi.setForeground(new java.awt.Color(255, 255, 255));
        tombolPesanKelasEkonomi.setText("Pesan Bus");
        tombolPesanKelasEkonomi.setAlignmentX(2.0F);
        tombolPesanKelasEkonomi.setAlignmentY(2.0F);
        tombolPesanKelasEkonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolPesanKelasEkonomiActionPerformed(evt);
            }
        });

        tombolCekHargaKelasEkonomi.setBackground(new java.awt.Color(102, 90, 72));
        tombolCekHargaKelasEkonomi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tombolCekHargaKelasEkonomi.setForeground(new java.awt.Color(255, 255, 255));
        tombolCekHargaKelasEkonomi.setText("Cek Harga");
        tombolCekHargaKelasEkonomi.setAlignmentX(2.0F);
        tombolCekHargaKelasEkonomi.setAlignmentY(2.0F);
        tombolCekHargaKelasEkonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCekHargaKelasEkonomiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ekonomiTabLayout = new javax.swing.GroupLayout(ekonomiTab);
        ekonomiTab.setLayout(ekonomiTabLayout);
        ekonomiTabLayout.setHorizontalGroup(
            ekonomiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ekonomiTabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(gambarBusEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ekonomiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombolPesanKelasEkonomi)
                    .addComponent(syaratKetentuanEkonomi)
                    .addGroup(ekonomiTabLayout.createSequentialGroup()
                        .addGroup(ekonomiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ekonomiTabLayout.createSequentialGroup()
                                .addGroup(ekonomiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelWaktuEksekutif1)
                                    .addComponent(labelTanggalEksekutif1)
                                    .addComponent(labelDewasa1))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ekonomiTabLayout.createSequentialGroup()
                                .addComponent(labelAnak1)
                                .addGap(18, 18, 18)))
                        .addGroup(ekonomiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jumlahDewasaEkonomi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(waktuEkonomi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tanggalEkonomi, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                            .addComponent(jumlahAnakEkonomi)))
                    .addGroup(ekonomiTabLayout.createSequentialGroup()
                        .addComponent(labelKelas1)
                        .addGap(18, 18, 18)
                        .addComponent(hargaKelasEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ekonomiTabLayout.createSequentialGroup()
                        .addComponent(labelTotal1)
                        .addGap(21, 21, 21)
                        .addComponent(hargaTotalEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombolCekHargaKelasEkonomi)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        ekonomiTabLayout.setVerticalGroup(
            ekonomiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ekonomiTabLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(ekonomiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ekonomiTabLayout.createSequentialGroup()
                        .addGroup(ekonomiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTanggalEksekutif1)
                            .addComponent(tanggalEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ekonomiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelWaktuEksekutif1)
                            .addComponent(waktuEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ekonomiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDewasa1)
                            .addComponent(jumlahDewasaEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ekonomiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlahAnakEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAnak1))
                        .addGap(18, 18, 18)
                        .addGroup(ekonomiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelKelas1)
                            .addComponent(hargaKelasEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ekonomiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTotal1)
                            .addComponent(hargaTotalEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolCekHargaKelasEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(gambarBusEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(syaratKetentuanEkonomi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tombolPesanKelasEkonomi)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        mainClassTab.addTab("KELAS EKONOMI", ekonomiTab);

        bisnisTab.setBackground(new java.awt.Color(255, 251, 233));

        gambarBusBisnis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bus bisnis.jpg"))); // NOI18N
        gambarBusBisnis.setPreferredSize(new java.awt.Dimension(490, 290));

        tanggalBisnis.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        tanggalBisnis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selasa, 11 Oktober 2022", "Rabu, 12 Oktober 2022", "Kamis, 13 Oktober 2022" }));
        tanggalBisnis.setToolTipText("");
        tanggalBisnis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        waktuBisnis.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        waktuBisnis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagi (08:00 WIB)", "Siang (13:30 WIB)" }));
        waktuBisnis.setToolTipText("");
        waktuBisnis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jumlahDewasaBisnis.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jumlahDewasaBisnis.setRequestFocusEnabled(false);

        jumlahAnakBisnis.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        hargaKelas2.setEditable(false);
        hargaKelas2.setColumns(20);
        hargaKelas2.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        hargaKelas2.setRows(5);
        hargaKelas2.setText("Anak-Anak\t: Rp125.000,00/orang\nDewasa\t: Rp150.000,00/orang");

        hargaTotalBisnis.setEditable(false);
        hargaTotalBisnis.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        hargaTotalBisnis.setText("Rp0");
        hargaTotalBisnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaTotalBisnisActionPerformed(evt);
            }
        });

        syaratKetentuanBisnis.setText("Saya menyetujui syarat dan ketentuan yang berlaku");

        labelTanggalEksekutif2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTanggalEksekutif2.setText("Pilih Tanggal");

        labelWaktuEksekutif2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelWaktuEksekutif2.setLabelFor(waktuEksekutif);
        labelWaktuEksekutif2.setText("Pilih Waktu");

        labelDewasa2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDewasa2.setText("Jumlah orang dewasa");

        labelAnak2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelAnak2.setText("Jumlah anak kecil (< 12)");

        labelKelas2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelKelas2.setText("Harga Kelas");

        labelTotal2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTotal2.setText("Total Bayar");

        tombolPesanKelasBisnis.setBackground(new java.awt.Color(102, 90, 72));
        tombolPesanKelasBisnis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tombolPesanKelasBisnis.setForeground(new java.awt.Color(255, 255, 255));
        tombolPesanKelasBisnis.setText("Pesan Bus");
        tombolPesanKelasBisnis.setAlignmentX(2.0F);
        tombolPesanKelasBisnis.setAlignmentY(2.0F);
        tombolPesanKelasBisnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolPesanKelasBisnisActionPerformed(evt);
            }
        });

        tombolCekHargaKelasBisnis.setBackground(new java.awt.Color(102, 90, 72));
        tombolCekHargaKelasBisnis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tombolCekHargaKelasBisnis.setForeground(new java.awt.Color(255, 255, 255));
        tombolCekHargaKelasBisnis.setText("Cek Harga");
        tombolCekHargaKelasBisnis.setAlignmentX(2.0F);
        tombolCekHargaKelasBisnis.setAlignmentY(2.0F);
        tombolCekHargaKelasBisnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCekHargaKelasBisnisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bisnisTabLayout = new javax.swing.GroupLayout(bisnisTab);
        bisnisTab.setLayout(bisnisTabLayout);
        bisnisTabLayout.setHorizontalGroup(
            bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bisnisTabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(gambarBusBisnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bisnisTabLayout.createSequentialGroup()
                            .addGroup(bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(bisnisTabLayout.createSequentialGroup()
                                    .addGroup(bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelWaktuEksekutif2)
                                        .addComponent(labelTanggalEksekutif2)
                                        .addComponent(labelDewasa2))
                                    .addGap(36, 36, 36))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bisnisTabLayout.createSequentialGroup()
                                    .addComponent(labelAnak2)
                                    .addGap(18, 18, 18)))
                            .addGroup(bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jumlahDewasaBisnis, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(waktuBisnis, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tanggalBisnis, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                                .addComponent(jumlahAnakBisnis))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bisnisTabLayout.createSequentialGroup()
                            .addGroup(bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelKelas2)
                                .addComponent(labelTotal2))
                            .addGap(18, 18, 18)
                            .addGroup(bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(bisnisTabLayout.createSequentialGroup()
                                    .addComponent(hargaTotalBisnis, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tombolCekHargaKelasBisnis)
                                    .addContainerGap(114, Short.MAX_VALUE))
                                .addGroup(bisnisTabLayout.createSequentialGroup()
                                    .addComponent(hargaKelas2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(bisnisTabLayout.createSequentialGroup()
                        .addGroup(bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tombolPesanKelasBisnis)
                            .addComponent(syaratKetentuanBisnis))
                        .addGap(106, 106, 106))))
        );
        bisnisTabLayout.setVerticalGroup(
            bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bisnisTabLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bisnisTabLayout.createSequentialGroup()
                        .addGroup(bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTanggalEksekutif2)
                            .addComponent(tanggalBisnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelWaktuEksekutif2)
                            .addComponent(waktuBisnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDewasa2)
                            .addComponent(jumlahDewasaBisnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlahAnakBisnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAnak2))
                        .addGap(18, 18, 18)
                        .addGroup(bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelKelas2)
                            .addComponent(hargaKelas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bisnisTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tombolCekHargaKelasBisnis, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaTotalBisnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotal2)))
                    .addComponent(gambarBusBisnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(syaratKetentuanBisnis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tombolPesanKelasBisnis)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        mainClassTab.addTab("KELAS BISNIS", bisnisTab);

        eksekutifTab.setBackground(new java.awt.Color(255, 251, 233));

        tanggalEksekutif.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        tanggalEksekutif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selasa, 11 Oktober 2022", "Rabu, 12 Oktober 2022", "Kamis, 13 Oktober 2022" }));
        tanggalEksekutif.setToolTipText("");
        tanggalEksekutif.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        waktuEksekutif.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        waktuEksekutif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagi (08:00 WIB)", "Siang (13:30 WIB)", "Malam (19:30 WIB)" }));
        waktuEksekutif.setToolTipText("");
        waktuEksekutif.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jumlahDewasaEksekutif.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jumlahDewasaEksekutif.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jumlahDewasaEksekutif.setName(""); // NOI18N
        jumlahDewasaEksekutif.setOpaque(true);
        jumlahDewasaEksekutif.setRequestFocusEnabled(false);

        jumlahAnakEksekutif.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        hargaKelas.setEditable(false);
        hargaKelas.setColumns(20);
        hargaKelas.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        hargaKelas.setRows(5);
        hargaKelas.setText("Anak-Anak\t: Rp175.000,00/orang\nDewasa\t: Rp200.000,00/orang");

        hargaTotalEksekutif.setEditable(false);
        hargaTotalEksekutif.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        hargaTotalEksekutif.setText("Rp0");
        hargaTotalEksekutif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaTotalEksekutifActionPerformed(evt);
            }
        });

        syaratKetentuanEksekutif.setText("Saya menyetujui syarat dan ketentuan yang berlaku");
        syaratKetentuanEksekutif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syaratKetentuanEksekutifActionPerformed(evt);
            }
        });

        labelTanggalEksekutif.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTanggalEksekutif.setText("Pilih Tanggal");

        labelWaktuEksekutif.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelWaktuEksekutif.setLabelFor(waktuEksekutif);
        labelWaktuEksekutif.setText("Pilih Waktu");

        labelDewasa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDewasa.setText("Jumlah orang dewasa");

        labelAnak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelAnak.setText("Jumlah anak kecil (< 12)");

        labelKelas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelKelas.setText("Harga Kelas");

        labelTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTotal.setText("Total Bayar");

        tombolPesanKelasEksekutif.setBackground(new java.awt.Color(102, 90, 72));
        tombolPesanKelasEksekutif.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tombolPesanKelasEksekutif.setForeground(new java.awt.Color(255, 255, 255));
        tombolPesanKelasEksekutif.setText("Pesan Bus");
        tombolPesanKelasEksekutif.setAlignmentX(2.0F);
        tombolPesanKelasEksekutif.setAlignmentY(2.0F);
        tombolPesanKelasEksekutif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolPesanKelasEksekutifActionPerformed(evt);
            }
        });

        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bus eksekutif.jpg"))); // NOI18N

        tombolCekHargaKelasEksekutif.setBackground(new java.awt.Color(102, 90, 72));
        tombolCekHargaKelasEksekutif.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tombolCekHargaKelasEksekutif.setForeground(new java.awt.Color(255, 255, 255));
        tombolCekHargaKelasEksekutif.setText("Cek Harga");
        tombolCekHargaKelasEksekutif.setAlignmentX(2.0F);
        tombolCekHargaKelasEksekutif.setAlignmentY(2.0F);
        tombolCekHargaKelasEksekutif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCekHargaKelasEksekutifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eksekutifTabLayout = new javax.swing.GroupLayout(eksekutifTab);
        eksekutifTab.setLayout(eksekutifTabLayout);
        eksekutifTabLayout.setHorizontalGroup(
            eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eksekutifTabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eksekutifTabLayout.createSequentialGroup()
                        .addGroup(eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tombolPesanKelasEksekutif)
                            .addComponent(syaratKetentuanEksekutif))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(eksekutifTabLayout.createSequentialGroup()
                        .addGroup(eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(eksekutifTabLayout.createSequentialGroup()
                                .addGroup(eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelKelas)
                                    .addComponent(labelTotal))
                                .addGap(18, 18, 18)
                                .addGroup(eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(eksekutifTabLayout.createSequentialGroup()
                                        .addComponent(hargaTotalEksekutif, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tombolCekHargaKelasEksekutif))
                                    .addComponent(hargaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(eksekutifTabLayout.createSequentialGroup()
                                .addGroup(eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(eksekutifTabLayout.createSequentialGroup()
                                        .addGroup(eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelWaktuEksekutif)
                                            .addComponent(labelTanggalEksekutif)
                                            .addComponent(labelDewasa))
                                        .addGap(36, 36, 36))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eksekutifTabLayout.createSequentialGroup()
                                        .addComponent(labelAnak)
                                        .addGap(18, 18, 18)))
                                .addGroup(eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jumlahDewasaEksekutif, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(waktuEksekutif, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tanggalEksekutif, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                                    .addComponent(jumlahAnakEksekutif))))
                        .addContainerGap(114, Short.MAX_VALUE))))
        );
        eksekutifTabLayout.setVerticalGroup(
            eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eksekutifTabLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eksekutifTabLayout.createSequentialGroup()
                        .addGroup(eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTanggalEksekutif)
                            .addComponent(tanggalEksekutif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelWaktuEksekutif)
                            .addComponent(waktuEksekutif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDewasa)
                            .addComponent(jumlahDewasaEksekutif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlahAnakEksekutif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAnak))
                        .addGap(18, 18, 18)
                        .addGroup(eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelKelas)
                            .addComponent(hargaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(eksekutifTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hargaTotalEksekutif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolCekHargaKelasEksekutif, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotal)))
                    .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(syaratKetentuanEksekutif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tombolPesanKelasEksekutif)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        mainClassTab.addTab("KELAS EKSEKUTIF", eksekutifTab);

        javax.swing.GroupLayout pemesananTabLayout = new javax.swing.GroupLayout(pemesananTab);
        pemesananTab.setLayout(pemesananTabLayout);
        pemesananTabLayout.setHorizontalGroup(
            pemesananTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemesananTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainClassTab)
                .addContainerGap())
        );
        pemesananTabLayout.setVerticalGroup(
            pemesananTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainClassTab, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        mainContent.addTab("PEMESANAN", pemesananTab);

        riwayatTab.setBackground(new java.awt.Color(255, 204, 153));

        tb_riwayat_pesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Waktu", "Orang Dewasa", "Anak-Anak", "Kelas", "Total Biaya"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_riwayat_pesanan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tb_riwayat_pesanan);

        btnLihatRiwayat.setText("Lihat Riwayat");
        btnLihatRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatRiwayatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout riwayatTabLayout = new javax.swing.GroupLayout(riwayatTab);
        riwayatTab.setLayout(riwayatTabLayout);
        riwayatTabLayout.setHorizontalGroup(
            riwayatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(riwayatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                    .addGroup(riwayatTabLayout.createSequentialGroup()
                        .addComponent(btnLihatRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        riwayatTabLayout.setVerticalGroup(
            riwayatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLihatRiwayat)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        mainContent.addTab("RIWAYAT", riwayatTab);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bus-school.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 230, 188));
        jLabel4.setText("ASMARALOKA TRAVEL (JAKARTA - BANDUNG)");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Bukan sekedar travel biasa, namun ini adalah tentang kenangan selama di perjalanan antara aku... dan dikau.");

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainContent)
                .addContainerGap())
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(34, 34, 34)
                .addComponent(mainContent)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void hargaTotalEksekutifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaTotalEksekutifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaTotalEksekutifActionPerformed

    private void hargaTotalBisnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaTotalBisnisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaTotalBisnisActionPerformed

    private void hargaTotalEkonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaTotalEkonomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaTotalEkonomiActionPerformed

    private void waktuEkonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktuEkonomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waktuEkonomiActionPerformed

    private void jadwalTabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jadwalTabFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jadwalTabFocusGained

    private void tombolPesanKelasEkonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolPesanKelasEkonomiActionPerformed
        // TODO add your handling code here:
        
        if (syaratKetentuanEkonomi.isSelected()) {
            String tanggal = tanggalEkonomi.getSelectedItem().toString();
            setTanggal(tanggal);  // Kita set tanggal untuk ditampung pada metode setter
            
            String waktu = waktuEkonomi.getSelectedItem().toString();
            setWaktu(waktu);  // Kita set waktu untuk ditampung pada metode setter
            setKelas("Ekonomi");
            this.setVisible(false);
            new Register().setVisible(true);  // Kita alihkan ke form registrasi data pemesan

        } else {
            JOptionPane.showMessageDialog(null, "Silakan centang syarat dan ketentuan terlebih dahulu!");
        }
    }//GEN-LAST:event_tombolPesanKelasEkonomiActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void tombolCekHargaKelasEkonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCekHargaKelasEkonomiActionPerformed
        // TODO add your handling code here:
        //Mengambil field dewasa dan anak
        int jmlhDewasa = (Integer) jumlahDewasaEkonomi.getValue();
        setJmlhDewasa(jmlhDewasa);  // Kita assign jumlah dewasa yang ikut
        
        int jmlhAnak = (Integer) jumlahAnakEkonomi.getValue();
        setJmlhAnak(jmlhAnak);  // Kita assign jumlah anak yang ikut


        //Mencari total harga
        int tempTotal = (jmlhDewasa * 100000) + (jmlhAnak * 75000);
        setTotalBayar(tempTotal);
        String hargaTotal = String.valueOf(tempTotal);
        hargaTotalEkonomi.setText("Rp" + hargaTotal);
    }//GEN-LAST:event_tombolCekHargaKelasEkonomiActionPerformed

    private void syaratKetentuanEkonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syaratKetentuanEkonomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_syaratKetentuanEkonomiActionPerformed

    private void tombolCekHargaKelasBisnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCekHargaKelasBisnisActionPerformed
        // TODO add your handling code here:
        //Mengambil field dewasa dan anak
        int jmlhDewasa = (Integer) jumlahDewasaBisnis.getValue();
        setJmlhDewasa(jmlhDewasa);  // Kita assign jumlah dewasa yang ikut
        
        int jmlhAnak = (Integer) jumlahAnakBisnis.getValue();
        setJmlhAnak(jmlhAnak);  // Kita assign jumlah anak yang ikut


        //Mencari total harga
        tempTotal = (jmlhDewasa * 150000) + (jmlhAnak * 125000);
        String hargaTotal = String.valueOf(tempTotal);
        hargaTotalBisnis.setText("Rp" + hargaTotal);
    }//GEN-LAST:event_tombolCekHargaKelasBisnisActionPerformed

    private void tombolCekHargaKelasEksekutifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCekHargaKelasEksekutifActionPerformed
        // TODO add your handling code here://Mengambil field dewasa dan anak
        int jmlhDewasa = (Integer) jumlahDewasaEksekutif.getValue();
        setJmlhDewasa(jmlhDewasa);  // Kita assign jumlah dewasa yang ikut
        
        int jmlhAnak = (Integer) jumlahAnakEksekutif.getValue();
        setJmlhAnak(jmlhAnak);  // Kita assign jumlah anak yang ikut


        //Mencari total harga
        tempTotal = (jmlhDewasa * 200000) + (jmlhAnak * 175000);
        String hargaTotal = String.valueOf(tempTotal);
        hargaTotalEksekutif.setText("Rp" + hargaTotal);
        
    }//GEN-LAST:event_tombolCekHargaKelasEksekutifActionPerformed

    private void tombolPesanKelasBisnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolPesanKelasBisnisActionPerformed
        // TODO add your handling code here:
         if (syaratKetentuanBisnis.isSelected()) {
            String tanggal = tanggalBisnis.getSelectedItem().toString();
            setTanggal(tanggal);  // Kita set tanggal untuk ditampung pada metode setter
            
            String waktu = waktuBisnis.getSelectedItem().toString();
            setWaktu(waktu);  // Kita set waktu untuk ditampung pada metode setter
            setTotalBayar(tempTotal);
            setKelas("Bisnis");
            this.setVisible(false);
            new Register().setVisible(true);  // Kita alihkan ke form registrasi data pemesan

        } else {
            JOptionPane.showMessageDialog(null, "Silakan centang syarat dan ketentuan terlebih dahulu!");
        }
    }//GEN-LAST:event_tombolPesanKelasBisnisActionPerformed

    private void syaratKetentuanEksekutifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syaratKetentuanEksekutifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_syaratKetentuanEksekutifActionPerformed

    private void tombolPesanKelasEksekutifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolPesanKelasEksekutifActionPerformed
        // TODO add your handling code here:
          if (syaratKetentuanEksekutif.isSelected()) {
            String tanggal = tanggalEksekutif.getSelectedItem().toString();
            setTanggal(tanggal);  // Kita set tanggal untuk ditampung pada metode setter
            
            String waktu = waktuEksekutif.getSelectedItem().toString();
            setWaktu(waktu);  // Kita set waktu untuk ditampung pada metode setter
            setTotalBayar(tempTotal);
            setKelas("Eksekutif");
            this.setVisible(false);
            new Register().setVisible(true);  // Kita alihkan ke form registrasi data pemesan

        } else {
            JOptionPane.showMessageDialog(null, "Silakan centang syarat dan ketentuan terlebih dahulu!");
        }
        
    }//GEN-LAST:event_tombolPesanKelasEksekutifActionPerformed

    private void btnLihatRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatRiwayatActionPerformed
        // TODO add your handling code here:
        String conn = connect();
        
        try {
            Connection connection = (Connection) DriverManager.getConnection(conn);
            
            Statement stmt = connection.createStatement();
            
            // mysql query
            String sql = "select * from tb_riwayat";
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()) {
                if (!String.valueOf(rs.getInt("id")).equals("")) {
                    String tanggal = rs.getString("tanggal");
                    String waktu = rs.getString("waktu");
                    String jlh_dewasa = String.valueOf(rs.getInt("jmlh_dewasa"));
                    String jlh_anak = String.valueOf(rs.getInt("jmlh_anak"));
                    String kelas = rs.getString("kelas");
                    String totalBiaya = String.valueOf(rs.getInt("total_bayar"));

                    // String array for storing data into table
                    String tbData[] = {tanggal, waktu, jlh_dewasa, jlh_anak, kelas, totalBiaya};
                    DefaultTableModel tblModel = (DefaultTableModel)tb_riwayat_pesanan.getModel();

                    // Add string array data into table
                    tblModel.addRow(tbData);
                } else {
                    JOptionPane.showMessageDialog(null, "Maaf Anda belum pernah memesan sebelumnya!");
                    break;
                }
               
            }
            
        } catch(SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnLihatRiwayatActionPerformed

    // Metode buatan untuk koneksi basis data
    private String connect() {
        String conn = "jdbc:mariadb://localhost:3306/db_pemesanan_bus?user=root&password=";
        return conn;
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    
    // Konstruktor
    
    
    //Setter dan Getter
    public String getTanggal() {
        return this.tanggal;
    }
    
    public String getWaktu() {
        return this.waktu;
    }
    
    public int getJmlhDewasa() {
        return this.jmlhDewasa;
    }
    
    public int getJmlhAnak() {
        return this.jmlhAnak;
    }
    
    public int getTotalBayar() {
        return this.totalBayar;
    }
    
    public String getKelas() {
        return this.kelas;
    }
    
    private void setKelas(String kelas) {
        this.kelas = kelas;
    }
    
    private void setTanggal(String tanggal){
        this.tanggal = tanggal;
    }
    
    private void setWaktu(String waktu){
        this.waktu = waktu;
    }
    
    private void setJmlhDewasa(int jmlhDewasa){
        this.jmlhDewasa = jmlhDewasa;
    }
    
    private void setJmlhAnak(int jmlhAnak){
        this.jmlhAnak = jmlhAnak;
    }
    
    private void setTotalBayar(int totalBayar) {
        this.totalBayar = totalBayar;
    }
    
    //My Own Variables
    private static String tanggal;
    private static String waktu;
    private static int jmlhDewasa;
    private static int jmlhAnak;
    private static int totalBayar;
    private static String kelas;
    private int tempTotal;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bisnisTab;
    private javax.swing.JButton btnLihatRiwayat;
    private javax.swing.JPanel container;
    private javax.swing.JPanel ekonomiTab;
    private javax.swing.JPanel eksekutifTab;
    private javax.swing.JLabel gambar;
    private javax.swing.JLabel gambarBusBisnis;
    private javax.swing.JLabel gambarBusEkonomi;
    private javax.swing.JTextArea hargaKelas;
    private javax.swing.JTextArea hargaKelas2;
    private javax.swing.JTextArea hargaKelasEkonomi;
    private javax.swing.JTextField hargaTotalBisnis;
    private javax.swing.JTextField hargaTotalEkonomi;
    private javax.swing.JTextField hargaTotalEksekutif;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel jadwalTab;
    private javax.swing.ButtonGroup jenisKelaminGrup;
    private javax.swing.JSpinner jumlahAnakBisnis;
    private javax.swing.JSpinner jumlahAnakEkonomi;
    private javax.swing.JSpinner jumlahAnakEksekutif;
    private javax.swing.JSpinner jumlahDewasaBisnis;
    private javax.swing.JSpinner jumlahDewasaEkonomi;
    private javax.swing.JSpinner jumlahDewasaEksekutif;
    private javax.swing.JLabel labelAnak;
    private javax.swing.JLabel labelAnak1;
    private javax.swing.JLabel labelAnak2;
    private javax.swing.JLabel labelDewasa;
    private javax.swing.JLabel labelDewasa1;
    private javax.swing.JLabel labelDewasa2;
    private javax.swing.JLabel labelKelas;
    private javax.swing.JLabel labelKelas1;
    private javax.swing.JLabel labelKelas2;
    private javax.swing.JLabel labelTanggalEksekutif;
    private javax.swing.JLabel labelTanggalEksekutif1;
    private javax.swing.JLabel labelTanggalEksekutif2;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTotal1;
    private javax.swing.JLabel labelTotal2;
    private javax.swing.JLabel labelWaktuEksekutif;
    private javax.swing.JLabel labelWaktuEksekutif1;
    private javax.swing.JLabel labelWaktuEksekutif2;
    private javax.swing.JTabbedPane mainClassTab;
    private javax.swing.JTabbedPane mainContent;
    private javax.swing.JPanel pemesananTab;
    private javax.swing.JPanel riwayatTab;
    private javax.swing.JCheckBox syaratKetentuanBisnis;
    private javax.swing.JCheckBox syaratKetentuanEkonomi;
    private javax.swing.JCheckBox syaratKetentuanEksekutif;
    private javax.swing.JComboBox<String> tanggalBisnis;
    private javax.swing.JComboBox<String> tanggalEkonomi;
    private javax.swing.JComboBox<String> tanggalEksekutif;
    private javax.swing.JTable tb_riwayat_pesanan;
    private javax.swing.JButton tombolCekHargaKelasBisnis;
    private javax.swing.JButton tombolCekHargaKelasEkonomi;
    private javax.swing.JButton tombolCekHargaKelasEksekutif;
    private javax.swing.JButton tombolPesanKelasBisnis;
    private javax.swing.JButton tombolPesanKelasEkonomi;
    private javax.swing.JButton tombolPesanKelasEksekutif;
    private javax.swing.JComboBox<String> waktuBisnis;
    private javax.swing.JComboBox<String> waktuEkonomi;
    private javax.swing.JComboBox<String> waktuEksekutif;
    // End of variables declaration//GEN-END:variables
}
