import javax.swing.JOptionPane;
import org.mariadb.jdbc.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.mariadb.jdbc.Statement;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author murafba
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkButtonGroup = new javax.swing.ButtonGroup();
        container = new javax.swing.JPanel();
        mainContent = new javax.swing.JTabbedPane();
        profilTab = new javax.swing.JPanel();
        fieldNama = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        lkButton = new javax.swing.JRadioButton();
        prButton = new javax.swing.JRadioButton();
        fieldAlamat = new javax.swing.JTextArea();
        labelNama = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelJenisKelamin = new javax.swing.JLabel();
        labelJudulProfil = new javax.swing.JLabel();
        labelNik = new javax.swing.JLabel();
        fieldNik = new javax.swing.JTextField();
        labelNik1 = new javax.swing.JLabel();
        fieldNoHp = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        submit1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(142, 128, 106));

        mainContent.setBackground(new java.awt.Color(173, 139, 115));
        mainContent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 128, 106), 2, true));
        mainContent.setForeground(new java.awt.Color(255, 251, 233));
        mainContent.setToolTipText("");
        mainContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainContent.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N

        profilTab.setBackground(new java.awt.Color(255, 237, 219));

        fieldNama.setBackground(new java.awt.Color(191, 146, 112));
        fieldNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fieldNama.setForeground(new java.awt.Color(255, 255, 255));
        fieldNama.setAlignmentX(1.5F);
        fieldNama.setAlignmentY(1.5F);
        fieldNama.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaActionPerformed(evt);
            }
        });

        fieldEmail.setBackground(new java.awt.Color(191, 146, 112));
        fieldEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fieldEmail.setForeground(new java.awt.Color(255, 255, 255));
        fieldEmail.setToolTipText("");
        fieldEmail.setAlignmentX(1.5F);
        fieldEmail.setAlignmentY(1.5F);
        fieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailActionPerformed(evt);
            }
        });

        jkButtonGroup.add(lkButton);
        lkButton.setSelected(true);
        lkButton.setText("Laki-Laki");

        jkButtonGroup.add(prButton);
        prButton.setText("Perempuan");

        fieldAlamat.setBackground(new java.awt.Color(191, 146, 112));
        fieldAlamat.setColumns(20);
        fieldAlamat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fieldAlamat.setForeground(new java.awt.Color(255, 255, 255));
        fieldAlamat.setRows(5);

        labelNama.setBackground(new java.awt.Color(153, 255, 102));
        labelNama.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        labelNama.setText("Nama");

        labelAlamat.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        labelAlamat.setText("Alamat");

        labelEmail.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        labelEmail.setText("Email");

        labelJenisKelamin.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        labelJenisKelamin.setText("Jenis Kelamin");

        labelJudulProfil.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelJudulProfil.setText("Profil Pengguna");

        labelNik.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        labelNik.setText("NIK");

        fieldNik.setBackground(new java.awt.Color(191, 146, 112));
        fieldNik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fieldNik.setForeground(new java.awt.Color(255, 255, 255));
        fieldNik.setAlignmentX(1.5F);
        fieldNik.setAlignmentY(1.5F);
        fieldNik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNikActionPerformed(evt);
            }
        });

        labelNik1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        labelNik1.setText("NO HP");

        fieldNoHp.setBackground(new java.awt.Color(191, 146, 112));
        fieldNoHp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fieldNoHp.setForeground(new java.awt.Color(255, 255, 255));
        fieldNoHp.setAlignmentX(1.5F);
        fieldNoHp.setAlignmentY(1.5F);
        fieldNoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNoHpActionPerformed(evt);
            }
        });

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        submit1.setText("Kembali");
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profilTabLayout = new javax.swing.GroupLayout(profilTab);
        profilTab.setLayout(profilTabLayout);
        profilTabLayout.setHorizontalGroup(
            profilTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilTabLayout.createSequentialGroup()
                .addGroup(profilTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilTabLayout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(labelJudulProfil))
                    .addGroup(profilTabLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addGroup(profilTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNik, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNik1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAlamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(profilTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profilTabLayout.createSequentialGroup()
                                .addComponent(lkButton)
                                .addGap(18, 18, 18)
                                .addComponent(prButton))
                            .addComponent(fieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(profilTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldEmail)
                                .addComponent(fieldNama)
                                .addComponent(fieldNik)
                                .addComponent(fieldNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(profilTabLayout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(submit)
                        .addGap(18, 18, 18)
                        .addComponent(submit1)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        profilTabLayout.setVerticalGroup(
            profilTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilTabLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(labelJudulProfil)
                .addGap(18, 18, 18)
                .addGroup(profilTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profilTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profilTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNik, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(profilTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilTabLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelNik1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(profilTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lkButton)
                            .addComponent(prButton)))
                    .addGroup(profilTabLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(fieldNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(profilTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profilTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submit)
                    .addComponent(submit1))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        mainContent.addTab("PROFIL", profilTab);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bus-school.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 230, 188));
        jLabel4.setText("ASMARALOKA TRAVEL");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Bukan sekedar travel biasa, namun ini adalah tentang kenangan selama di perjalanan antara aku... dan dikau.");

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainContent)
                .addContainerGap())
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(34, 34, 34)
                .addComponent(mainContent)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if(fieldNama.getText().equals("") || fieldEmail.getText().equals("") || fieldNik.getText().equals("") || 
                fieldNoHp.getText().equals("") || fieldAlamat.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Mohon untuk mengisi seluruh data-data terlebih dahulu!");
        } else {
           String conn = connect();
           int confirm = 0;
           
           confirm = JOptionPane.showConfirmDialog(null, "Apa Anda sudah yakin dengan data-data yang Anda masukkan?", 
                   "Apa Anda sudah yakin?", JOptionPane.YES_NO_OPTION);
           
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    Connection connection = (Connection) DriverManager.getConnection(conn);
                    // Import java.sql.ResultSet;
                    // ResultSet rs;
                    
                    // Import org.mariadb.jdbc.Statement
                    Statement stmt;
                    
                    // Get value from the registration form
                    String nama = fieldNama.getText();
                    String email = fieldEmail.getText();
                    String nik = fieldNik.getText();
                    String noHp = fieldNoHp.getText();
                    String alamat = fieldAlamat.getText();
                    String jk;
                    
                    if(lkButton.isSelected()) {
                        jk = lkButton.getText();
                    } else {
                        jk = prButton.getText();
                    }
                    
                    // Get value from the MainForm
                    MainForm mainFormData = new MainForm();
                    String tanggal = mainFormData.getTanggal();
                    String waktu = mainFormData.getWaktu();
                    int jmlhDewasa = mainFormData.getJmlhDewasa();
                    int jmlhAnak = mainFormData.getJmlhAnak();
                    int totalHarga = mainFormData.getTotalBayar();
                    String kelas = mainFormData.getKelas();
                    
                   
                    String SQL;
                    stmt = connection.createStatement();
                    
                    // Insert tb_akun
                    SQL = "insert into tb_akun values (NULL,\'" + nama + "\',\'" + email + "\',\'" + nik + "\',\'" + noHp + "\',\'" + jk + "\',\'" + alamat  + "\')";
                    int rs_num = stmt.executeUpdate(SQL);
                    
                    // Insert tb_riwayat
                    SQL = "insert into tb_riwayat values (NULL,\'" + tanggal + "\',\'" + waktu + "\',\'" + jmlhDewasa + "\',\'" + jmlhAnak + "\',\'" + kelas + "\',\'" + totalHarga + "\')";
                    rs_num = stmt.executeUpdate(SQL);
                    
                    JOptionPane.showMessageDialog(null, "Anda sudah berhasil memesan! Silakan datang ke terminal pada waktu yang telah dipilih."); 
                    this.setVisible(false);
                    new MainForm().setVisible(true);  // Kita alihkan ke MainForm

                } catch (SQLException ex) {
               
                }
            } else if (confirm == JOptionPane.NO_OPTION) {
                this.setVisible(false);
                new MainForm().setVisible(true);  // Kita alihkan ke MainForm
            }
           
           
          
        }
    }//GEN-LAST:event_submitActionPerformed

    private void fieldNoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNoHpActionPerformed

    private void fieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaActionPerformed

    private void fieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailActionPerformed

    private void fieldNikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNikActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainForm().setVisible(true);  // Kita alihkan ke MainForm
    }//GEN-LAST:event_submit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }
    
    
    // Koneksi ke database
    private String connect() {
        String conn = "jdbc:mariadb://localhost:3306/db_pemesanan_bus?user=root&password=";
        return conn;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JTextArea fieldAlamat;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldNik;
    private javax.swing.JTextField fieldNoHp;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.ButtonGroup jkButtonGroup;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelJenisKelamin;
    private javax.swing.JLabel labelJudulProfil;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNik;
    private javax.swing.JLabel labelNik1;
    private javax.swing.JRadioButton lkButton;
    private javax.swing.JTabbedPane mainContent;
    private javax.swing.JRadioButton prButton;
    private javax.swing.JPanel profilTab;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit1;
    // End of variables declaration//GEN-END:variables
}
